config/routes.rb
Rails.application.routes.draw do
  
  root 'orders#index'
  
  resources :orders do 
    member do 
      post :vote
    end
    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  get '/orders' => 'orders#index'
  get '/orders/new' => 'orders#new'
  post '/orders' => 'orders#create'
  # get '/forums' => 'forums#index'
  # get '/forums/new' => 'forums#new'
  # post '/forums' => 'forums#create'
  # get '/forums/:id/edit' => 'forums#edit'
  # get '/forums/:id' => 'forums#show'
  # get '/contents' => 'contents#index'
  # get '/contents/new' => 'contents#new'
  # post '/contents' => 'contents#create'
  # get '/contents/:id' => 'contents#show', as: :content
  # get '/contents/:id/edit' => 'contents#edit'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :contents
  resources :forums


  resources :users, only: [:new, :create]
  get '/register', to: 'users#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/forum.rb
class Forum < ApplicationRecord
    belongs_to :user
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
    before_action :set_forum, only: [:show, :edit, :update, :destroy]

    def index
        @forums = Forum.all
    end

    def show
        
    end

    def new
        @forum = Forum.new
    end

    def edit
    end

    def create 
        @forum = Forum.new({issue: params[:issue], description: params[:description]})
        @forum.user = current_user

        if @forum.save
            redirect_to @forum
        else
            render :new
        end
    end

    def update
        respond_to do |format|
            if @forum.update(forum_params)
                format.html { redirect_to @forum, notice: 'Forum was successfully updated!' }
                format.json { render :show, status: :ok, location: @forum }
            else
                format.html { render :edit }
                format.json { render json: @forum.errors, status: :unprocessable_entity }
            end 
        end
    end

    def destroy
        @forum.destroy
        respond_to do |format|
            format.html { redirect_to forums_url, notice: 'Forum was successfull destroyed.' }
            format.json { head :no_content }
        end
    end

    private

        def set_forum
            @forum = Forum.find(params[:id])
        end

        def forum_params
            params.require(:forum).permit(:issue, :description)
        end
end

app/views/forums/_form.html.erb
<%= form_for(forum) do |f| %>
  <% if forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(forum.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% forum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :issue %>
    <%= f.text_field :issue %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forums/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', forum: @forum %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<p id="notice"><%= notice %></p>

<%= render '/shared/title', title: "討論區" %>

<%= link_to 'Ask Something...', new_forum_path, class: 'btn btn-warning' %>
<hr>

<% @forums.each do |forum| %>
<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <h2><strong><a datd-toggle="collapse" data-parent="#accordion" href="#collapse1">Q: <%= forum.issue %></a></strong></h2>
      </h4>
    </div>
    <div id="collapse1" class="panel-collapse collapse in">
      <div class="panel-body" style="word-break: break-all"> <%#word-break 自動換行%>
        <%= forum.description %>
      </div>
        <%= link_to 'Answer!', forum_path(forum), class: 'btn btn-success' %>
        <% if logged_in? %>
          <%= link_to 'Edit', edit_forum_path(forum), class: 'btn btn-info' %>
          <%= link_to 'Destroy', forum, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/forums/new.html.erb
<%= render '/shared/title', title: 'Ask Anything!' %>

<div class="well col-md-6">
  <%= form_for @forum do |f| %>
  <div class="form-group">
    <%= label_tag :issue %>
    <br>
    <%= f.text_field :issue %>
  </div>
  <div class="form-group">
    <%= label_tag :description %>
    <br>
    <%= f.text_area :description %>
  </div>
  <br>
  <%= f.submit class: 'btn btn-success' %>
  <% end %>
</div>

app/views/forums/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>Issue</th>
      <th>Description</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @forum.issue %></td>
        <td><%= @forum.description %></td>
      </tr>
  </tbody>
</table>



<% if logged_in? %>
<%= link_to 'Edit', edit_forum_path(@forum), class: 'btn btn-default' %> |
<% end %>
<%= link_to 'Back', forums_path, class: 'btn btn-default' %>