config/routes.rb
Rails.application.routes.draw do
  
  root 'orders#index'
  
  resources :orders do 
    member do 
      post :vote
    end
    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  get '/orders' => 'orders#index'
  get '/orders/new' => 'orders#new'
  post '/orders' => 'orders#create'
  # get '/forums' => 'forums#index'
  # get '/forums/new' => 'forums#new'
  # post '/forums' => 'forums#create'
  # get '/forums/:id/edit' => 'forums#edit'
  # get '/forums/:id' => 'forums#show'
  # get '/contents' => 'contents#index'
  # get '/contents/new' => 'contents#new'
  # post '/contents' => 'contents#create'
  # get '/contents/:id' => 'contents#show', as: :content
  # get '/contents/:id/edit' => 'contents#edit'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :contents
  resources :forums


  resources :users, only: [:new, :create]
  get '/register', to: 'users#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/content.rb
class Content < ApplicationRecord
    belongs_to :user
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
    before_action :set_content, only: [:show, :edit, :update, :destroy]

    def index
        @contents = Content.all
    end

    def new 
        @content = Content.new
    end

    def show
    end

    def edit
    end

    def create
        #@content = Content.new({nickname: params[:nickname], title: params[:title], essay: params[:essay]})
        # @content.user = current_user
        @content = Content.new(content_params)
        @content.user = current_user

        if @content.save
            redirect_to content_path(@content)
        else
            render :new
        end
    end

    def update 
        respond_to do |format|
            if @content.update(content_params)
                format.html { redirect_to @content, notice: 'Essay was successfully updated!' }
                format.json { render :show, status: :ok, location: @content }
            else
                format.html { render :edit }
                format.json { render json: @content.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @content.destroy
        respond_to do |format|
            format.html { redirect_to contents_url, notice: 'Essay was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private

        def set_content
            @content = Content.find(params[:id])
        end
        
        def content_params
            params.require(:content).permit(:title, :essay, :nickname)
        end
end

app/views/contents/_form.html.erb
<%= form_for(content) do |f| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nickname %>
    <%= f.text_field :nickname %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :essay %>
    <%= f.text_area :essay %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Essay</h1>

<%= render 'form', content: @content %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<%= render '/shared/title', title: "精選內容" %>
<% if logged_in? %>
<%= link_to 'New Post', new_content_path, class: 'btn btn-warning' %>
<hr>
<% end %>

<% @contents.each do |content| %>
<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <h2><strong><center><a datd-toggle="collapse" data-parent="#accordion" href="#collapse1"><%= content.title %> | <%= content.nickname%></a></center></strong></h2>
      </h4>
    </div>
    <div id="collapse1" class="panel-collapse collapse in">
      <div class="panel-body" style="word-break: break-all"> <%#word-break 自動換行%>
        <center><%= content.essay %></center>
      </div>
        <%= link_to 'Read More', content, class: 'btn btn-info' %><span>
        <% if logged_in? %>
          <%= link_to 'Edit', edit_content_path(content), class: 'btn btn-success' %><span>
          <%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %><span>
        <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/contents/new.html.erb
<%= render '/shared/title', title: 'New Essay!' %>

<div class="well col-md-6">
  <%= form_for @content do |f| %>
  <div class="form-group">
    <%= label_tag :nickname %>
    <br>
    <%= f.text_field :nickname %>
  </div>
  <div class="form-group">
    <%= label_tag :title %>
    <br>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= label_tag :essay %>
    <br>
    <%= f.text_area :essay %>
  </div>
  <br>
  <%= f.submit class: 'btn btn-success' %>
  <% end %>
</div>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>標題</th>
      <th>內文</th>
      <th>作者</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @content.title %></td>
        <td><%= @content.essay %></td>
        <td><%= @content.nickname%></td>
      </tr>
  </tbody>
</table>

<!--
<hr>

<%# @comments.each do |comment| %>
  <div class="row well">
    <p>
      <%#= comment.user.name %> : 
      <%#= comment.content %>
    </p>
  </div>
<%# end %>


-->

<% if logged_in? %>
<%= link_to 'Edit', edit_content_path(@content), class: 'btn btn-default' %> |
<% end %>
<%= link_to 'Back', contents_path, class: 'btn btn-default' %>