config/routes.rb
Rails.application.routes.draw do
  
  root 'orders#index'
  
  resources :orders do 
    member do 
      post :vote
    end
    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  get '/orders' => 'orders#index'
  get '/orders/new' => 'orders#new'
  post '/orders' => 'orders#create'
  # get '/forums' => 'forums#index'
  # get '/forums/new' => 'forums#new'
  # post '/forums' => 'forums#create'
  # get '/forums/:id/edit' => 'forums#edit'
  # get '/forums/:id' => 'forums#show'
  # get '/contents' => 'contents#index'
  # get '/contents/new' => 'contents#new'
  # post '/contents' => 'contents#create'
  # get '/contents/:id' => 'contents#show', as: :content
  # get '/contents/:id/edit' => 'contents#edit'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :contents
  resources :forums


  resources :users, only: [:new, :create]
  get '/register', to: 'users#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

    has_many :comments
    belongs_to :user
    has_many :votes, as: :voteable
    validates :name, presence: true
    validates :phone, presence: true
    validates :description, presence: true

    def up_votes
        self.votes.where(vote: true).length
    end
    
    def down_votes
        self.votes.where(vote: false).length
    end

    def total_votes
        up_votes - down_votes
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  #  @order = Order.new
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @comment = Comment.new
    @comments = @order.comments
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  def vote
    @order = Order.find(params[:id])
    @vote = Vote.create(voteable: @order, creator: current_user, vote: params[:vote])
    
    redirect_to root_path
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.user = current_user

    if @order.save
      flash[:success] = "order created!"
      redirect_to order_path(@order)
    else
      flash[:danger] = "you forgot to enter some data!"
      render :new
    end

    # respond_to do |format|
    #   if @order.save
    #     format.html { redirect_to @order, notice: 'Order was successfully created.' }
    #     format.json { render :show, status: :created, location: @order }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @order.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :phone, :description)
    end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% if controller.action_name == "new" %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field(:name, value: current_user.name) %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field(:phone, value: current_user.phone) %>
  </div>
<% else %> 
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
<% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<%= render '/shared/title', title: "Featured Courses" %>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Topic</th>
      <th>Classify</th>
      <th>Description</th>
      <th colspan="3">Likes</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><h4><strong><%= order.name %></h4><strong></td>
        <td><%= order.phone %></td>
        <td><%= order.description %></td>
        <td><%= order.total_votes %></td>
        <td>
          <%= link_to vote_order_path(order, vote: true), class: "btn btn-primary", method: 'post' do %>
          <h4>👍</h4>
          <% end %>
        </td>
        <td>
          <%= link_to vote_order_path(order, vote: false), class: "btn btn-danger", method: 'post' do %>
          <h4>🔫</h4>
          <% end %>
        </td>
        <td><%= link_to 'Apply', order, class: 'btn btn-info' %></td>
        <% if logged_in? %>
          <td><%= link_to 'Edit', edit_order_path(order), class: 'btn btn-success' %></td>
          <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path, class: 'btn btn-warning' %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= form_for @order do |f| %>

    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control col-sm-3', value: current_user.name %>
    </div>

    <div class="form-group">
        <%= f.label :phone %>
        <%= f.text_field :phone, class: 'form-control col-sm-3' %>
    </div>

    

    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control col-sm-3', placeholder: 'I want order...' %>
    </div>

    <div class="actions">
        <%= f.submit class: 'btn btn-primary' %>
    </div>

    

<% end %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @order.name %></td>
        <td><%= @order.phone %></td>
        <td><%= @order.description %></td>
      </tr>
  </tbody>
</table>

<hr>

<% @comments.each do |comment| %>
  <div class="row well">
    <p>
      <%= comment.user.name %> : 
      <%= comment.content %>
    </p>
  </div>
<% end %>

<%= form_for([@order, @comment]) do |f| %>
  <div class="row">
    <%= f.text_area :content, rows: 3, class: 'col-md-4' %>
    <div class="col-md-2">
      <%= f.submit 'comment', class: 'btn btn-primary'%>
    </div>
  </div>
  <br>
<% end %>

<% if logged_in? %>
<%= link_to 'Edit', edit_order_path(@order), class: 'btn btn-default' %> |
<% end %>
<%= link_to 'Back', orders_path, class: 'btn btn-default' %>