config/routes.rb
Rails.application.routes.draw do
  
  root 'orders#index'
  
  resources :orders do 
    member do 
      post :vote
    end
    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  get '/orders' => 'orders#index'
  get '/orders/new' => 'orders#new'
  post '/orders' => 'orders#create'
  # get '/forums' => 'forums#index'
  # get '/forums/new' => 'forums#new'
  # post '/forums' => 'forums#create'
  # get '/forums/:id/edit' => 'forums#edit'
  # get '/forums/:id' => 'forums#show'
  # get '/contents' => 'contents#index'
  # get '/contents/new' => 'contents#new'
  # post '/contents' => 'contents#create'
  # get '/contents/:id' => 'contents#show', as: :content
  # get '/contents/:id/edit' => 'contents#edit'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :contents
  resources :forums


  resources :users, only: [:new, :create]
  get '/register', to: 'users#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <%= link_to "DataMixContent LAB", root_path, class: 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <% if logged_in? %>
                    <li><%= link_to "申請課程", new_order_path %></li>
                    <li><%= link_to "精選內容", contents_path %></li>
                    <li><%= link_to "討論區", forums_path %></li>
                <% else %>
                    <li><%= link_to "註冊", register_path %></li>
                    <li><%= link_to "精選內容", contents_path %></li>
                    <li><%= link_to "討論區", forums_path %></li>
                <% end %>   
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <% if logged_in? %>
                    <li class="dropdown">
                        <%= link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown' do %>
                            <%= current_user.name %> <span class='caret'></span>
                        <% end %>
                        <ul class="dropdown-menu">
                            <li class="divider" role="separator"></li>
                            <li><%= link_to "登出", logout_path %></li>
                        </ul>
                    </li>    
                <% else %>
                    <li><%= link_to "登入", login_path %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HungryBee</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
  
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </body>
</html>